<?php

namespace Database\Seeders;

use App\Models\Member;
use App\Models\MemberContact;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class MemberContactSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Hardcoded member contacts data from static HTML
        $contacts = [
            // WÜRDENTRÄGER
            [
                'rank_abbreviation' => 'OÄ',
                'member_name' => 'Tüftel der experimentelle Narrenspross',
                'member_title_details' => 'Rkch, ErbW, OR, (6.1.144)',
                'real_name' => 'RUBBA Klaus (Maki)',
                'profession' => 'Informatiker',
                'birth_date' => Carbon::create(1974, 6, 18),
                'address' => '10823 - 134 Steet NW, Edmonton, AB, T5M 1H9',
                'phone_home' => '7804886214',
                'phone_cell' => '7806550958',
                'email' => 'krubba@gmail.com',
                'category' => 'WÜRDENTRÄGER',
                'sort_order' => 0,
            ],
            [
                'rank_abbreviation' => 'OK',
                'member_name' => 'Java der vernetzliche Spinner',
                'member_title_details' => 'LBo, OR, (6.4.139)',
                'real_name' => 'RUBBA Victor (Cindy)',
                'profession' => 'Computer Fachberater',
                'birth_date' => Carbon::create(1970, 11, 5),
                'address' => '1756 Haswell Cove NW, EDMONTON, AB, T6R 3A9',
                'phone_home' => '7807012849',
                'phone_fax' => '7807077393',
                'email' => 'victor@rubba.com',
                'category' => 'WÜRDENTRÄGER',
                'sort_order' => 1,
            ],
            [
                'rank_abbreviation' => 'K',
                'member_name' => 'Weswolf der palmström\'sche Genitiv',
                'member_title_details' => 'Sbw, Rpst, Rpb, OR, (30.4.153)',
                'real_name' => 'FODOR Christopher',
                'profession' => 'Kalibrierungs-Techniker',
                'birth_date' => Carbon::create(1986, 10, 21),
                'address' => 'Unit 201, 2303-119 Street NW, EDMONTON, AB,  T6J 4E2',
                'phone_cell' => '7803405510',
                'email' => 'cfodor@hotmail.ca',
                'category' => 'WÜRDENTRÄGER',
                'sort_order' => 2,
            ],
            [
                'rank_abbreviation' => 'M',
                'member_name' => 'Blarneycus der schnelle Glöckner',
                'member_title_details' => 'Urs, ErbWA, ErbM WA, P, OR, (5.3.148)',
                'real_name' => 'GRAHAM John (Jackie)',
                'profession' => 'Ingenieur',
                'birth_date' => Carbon::create(1952, 1, 24),
                'address' => '402 Butchart Drive NW, EDMONTON, AB, T6R 1P9',
                'phone_home' => '7809885612',
                'phone_fax' => '7804344452',
                'email' => 'Mrmitre@shaw.ca',
                'category' => 'WÜRDENTRÄGER',
                'sort_order' => 3,
            ],
            [
                'rank_abbreviation' => 'J',
                'member_name' => 'Wat-n-dat die elementare Verbindung',
                'member_title_details' => 'Md, Rkll, OR (2.5.157)',
                'real_name' => 'SEIDEL Wolfram (Natascha)',
                'profession' => 'Tischler',
                'birth_date' => Carbon::create(1974, 9, 29),
                'address' => '9384 - 123 Street NW, EDMONTON, AB, T5T 1K7',
                'phone_home' => '7807560294',
                'phone_cell' => '7808501974',
                'email' => 'wolframseidel@rocketmail.com',
                'category' => 'WÜRDENTRÄGER',
                'sort_order' => 4,
            ],
            [
                'rank_abbreviation' => 'Sch',
                'member_name' => 'Tetrapylo der Friedensstifter',
                'member_title_details' => 'Rs, Sm, OR, (25.4.149)',
                'real_name' => 'LOU Marco (Gail)',
                'profession' => 'Kriminalbeamter RCMP',
                'birth_date' => Carbon::create(1971, 7, 21),
                'address' => '# 5 Range Road 53104, STONY PLAIN, AB, T7Y 2T2',
                'phone_home' => '7805151433',
                'email' => 'marco.travler@gmail.com',
                'category' => 'WÜRDENTRÄGER',
                'sort_order' => 5,
            ],
            [
                'rank_abbreviation' => 'C',
                'member_name' => '"Unser" Wing-Wing der fliegreyche Atmosphärenschreck',
                'member_title_details' => 'ASR (149-154), SRNA (149-154), LVDCB, NLSI-2, NLPC-2, Urs, Erb, ErbRbe, Km, Hfm, Hfn, Rbe, ErbO, ErbC, ER 372, 415, silb. V.Med. LVNA (6.3.130)',
                'real_name' => 'MÜRRLE Thomas',
                'profession' => 'Pilot',
                'birth_date' => Carbon::create(1951, 7, 2),
                'address' => '9308 - 82 Street NW, EDMONTON, AB, T6C 2X5',
                'phone_home' => '7804682728',
                'phone_cell' => '7809372751',
                'email' => 'wingwing337@gmail.com',
                'category' => 'WÜRDENTRÄGER',
                'sort_order' => 6,
            ],
            
            // ERBWÜRDENTRÄGER IM RUHESTAND
            [
                'rank_abbreviation' => null,
                'member_name' => 'Beton-Narr der Hochgebaute',
                'member_title_details' => 'LBCS, LBo, GU, Erb, ErbT, ErbO, Km, WS, B, T, ER 126, (7.3.129)',
                'real_name' => 'RUBBA Herbert (Christine)',
                'profession' => 'Bauführer',
                'birth_date' => Carbon::create(1942, 12, 13),
                'address' => '253-51308 Range Road 224, SHERWOOD PARK, AB, T8C 1H3',
                'phone_home' => '7809223665',
                'email' => 'chrisubba@yahoo.ca',
                'category' => 'ERBWÜRDENTRÄGER IM RUHESTAND',
                'sort_order' => 7,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => '"Unser" Jan Maat der Alsterpirat',
                'member_title_details' => 'ASR (125-135), SRNA (124-135), LB-2, LBa, LV-4, LCA, LL, NLDN, NLFC-2, NLFL, NLBI, NLLC, NLSI-2, NLPC-2, NLDN-2, GU, Erb, Km, ErbO, ErbK, ErbRpst, ErbRbe, Rp, OR, ER 198, 229, 372, 387, 403, 406, 408, Kolumbusritter II, (6.3.108)',
                'real_name' => 'ANIELSKI Hans-Ulrich (Mary Ann)',
                'profession' => 'Importeur',
                'birth_date' => Carbon::create(1935, 11, 25),
                'address' => '142 Haddow Close NW, EDMONTON, AB, T6R 2T9',
                'phone_home' => '7804383408',
                'email' => 'janmaat337@gmail.com',
                'category' => 'ERBWÜRDENTRÄGER IM RUHESTAND',
                'sort_order' => 8,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Lex tempore der Rehseesegler',
                'member_title_details' => 'GU, Erb, Km, ErbO, SR, (6.11.130)',
                'real_name' => 'KUEHN Peter (Dagmar)',
                'profession' => 'Rechtsanwalt & Notar',
                'birth_date' => Carbon::create(1937, 9, 20),
                'address' => '109 Twin Brooks Cove NW, EDMONTON, AB, T6J 6T1',
                'phone_home' => '7804340491',
                'category' => 'ERBWÜRDENTRÄGER IM RUHESTAND',
                'sort_order' => 9,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Schöppche der Offe-Becher',
                'member_title_details' => 'SRNA (159-), LK, LVDCB, LTr, LBCS, LBo, NLSI-2, NLDN-2, NLNO, Urs, Erb, Km, ErbA, ErbK, ErbRpb, ErbRpst, A, Chr, Btr, NV, ER 126, 293, 372, 415, silb. V.Med. LVNA (6.3.136)',
                'real_name' => 'MACK Klaus (Anita)',
                'profession' => 'Service Manager',
                'birth_date' => Carbon::create(1954, 3, 22),
                'address' => '20710 - 9 Avenue SW, EDMONTON, AB, T6M 2N9',
                'phone_home' => '7804445081',
                'phone_fax' => '7804623111',
                'email' => 'mack.klaus.anita@gmail.com',
                'category' => 'ERBWÜRDENTRÄGER IM RUHESTAND',
                'sort_order' => 10,
            ],
            
            // SESSHAFTE RITTER
            [
                'rank_abbreviation' => null,
                'member_name' => 'Phil-o-atz Genie(s)er von Al-too-na',
                'member_title_details' => 'Brill. z. GU, Erb, Km, ErbBtr (6.2.108)',
                'real_name' => 'SINTENIS Ingo',
                'profession' => 'Ingenieur i.R.',
                'birth_date' => Carbon::create(1931, 6, 26),
                'address' => '2000 Fairview Court, SHERWOOD PARK, AB, T8A 0Y8',
                'phone_home' => '7804675692',
                'category' => 'SESSHAFTE RITTER',
                'sort_order' => 11,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Rädle der eiernde Bioniker',
                'member_title_details' => '(18.4.152)',
                'real_name' => 'BASLER Hermann (Irmgard)',
                'profession' => 'Ingenieur',
                'birth_date' => Carbon::create(1959, 2, 28),
                'address' => '27521 Twp Rd 514, Parkland County, AB, T7Y 2X4',
                'phone_home' => '7809639069',
                'phone_cell' => '7802224759',
                'email' => 'tms.basler@gmail.com',
                'category' => 'SESSHAFTE RITTER',
                'sort_order' => 12,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Seekular das digitale Auge',
                'member_title_details' => '(5.12.146)',
                'real_name' => 'von ROEDER Philipp',
                'profession' => 'Dipl. Ing.',
                'birth_date' => Carbon::create(1951, 10, 22),
                'address' => 'P.O.Box 3584, SPRUCE GROVE, AB, T7X 3A8',
                'phone_cell' => '7809995149',
                'email' => 'seekular@rvd-online.de',
                'category' => 'SESSHAFTE RITTER',
                'sort_order' => 13,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Wildschütz Orvis vom Felsensee',
                'member_title_details' => 'Gu, H, Rp, T (5.3.148)',
                'real_name' => 'HOFMANN Hubert (Yvonne)',
                'profession' => 'Supervisor Chem. Research i.R.',
                'birth_date' => Carbon::create(1942, 10, 28),
                'address' => '9820 - 167 Street NW, EDMONTON, AB, T5P 3V9',
                'phone_home' => '7804844518',
                'email' => 'hhofmann@telus.net',
                'category' => 'SESSHAFTE RITTER',
                'sort_order' => 14,
            ],
            
            // JUNKER UND KNAPPEN
            [
                'rank_abbreviation' => null,
                'member_name' => 'Junker Hans',
                'member_title_details' => '(3.2.161)',
                'real_name' => 'ZÜRCHER Hans',
                'profession' => 'Rentner',
                'birth_date' => Carbon::create(1942, 12, 17),
                'address' => '31-51528 Rge Rd 262, SPRUCE GROVE, AB,  T7Y 1C1',
                'phone_home' => '7804184267',
                'email' => 'hanszurcher@hotmail.com',
                'category' => 'JUNKER UND KNAPPEN',
                'sort_order' => 15,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Kn 121',
                'member_title_details' => null,
                'real_name' => 'KLASSEN Jeremy',
                'profession' => 'Lehrer',
                'birth_date' => Carbon::create(1973, 11, 15),
                'address' => '8015 - 183 Street NW, EDMONTON, AB, T5T 0T9',
                'phone_home' => '7804619646',
                'phone_cell' => '7809379646',
                'email' => 'jeremyklassen314@gmail.com',
                'category' => 'JUNKER UND KNAPPEN',
                'sort_order' => 16,
            ],
            
            // PILGER
            [
                'rank_abbreviation' => null,
                'member_name' => 'Pilger',
                'member_title_details' => null,
                'real_name' => 'NEUMEISTER Matthias',
                'profession' => 'Kamerabühnenassistent',
                'birth_date' => Carbon::create(1991, 12, 31),
                'address' => 'Bürgerheimstraße 15, 10365 BERLIN',
                'phone_cell' => '4915774195634',
                'email' => 'matthiasneumeister@gmx.net',
                'category' => 'PILGER',
                'sort_order' => 17,
            ],
            
            // PRÜFLINGE
            [
                'rank_abbreviation' => null,
                'member_name' => 'Prüfling',
                'member_title_details' => null,
                'real_name' => 'LÜCKE Dennis (Lisa)',
                'profession' => 'Bäcker',
                'birth_date' => Carbon::create(1987, 10, 17),
                'address' => '5111 - 51 Ave, Stony Plain, AB, T7Z 1C2',
                'phone_home' => '7809749347',
                'email' => 'de.luecke@web.de',
                'category' => 'PRÜFLINGE',
                'sort_order' => 18,
            ],
            
            // FAHRENDE
            [
                'rank_abbreviation' => null,
                'member_name' => 'Abooki der ugandische Quacksalber',
                'member_title_details' => 'Z (2.2.150)',
                'real_name' => 'KIPP Walter (Jean)',
                'profession' => 'Prof. f. internationales Gesundheitswesen',
                'birth_date' => Carbon::create(1945, 5, 14),
                'address' => '3065 County Road 7, PICTON, ON, K0K 2T0',
                'phone_home' => '6134711736',
                'phone_cell' => '5873402747',
                'email' => 'susiekipp@gmail.com',
                'category' => 'FAHRENDE',
                'sort_order' => 19,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Baltenherz der Hördelsche',
                'member_title_details' => 'GU, Erb, Km, ErbO, (31.10.124)',
                'real_name' => 'Freiherr von STACKELBERG, Hans Ernst (Irene)',
                'profession' => 'Psychologe',
                'birth_date' => Carbon::create(1934, 11, 28),
                'address' => '10953 - 70 Avenue NW, EDMONTON, AB, T6H 2G7',
                'phone_home' => '7804363221',
                'phone_fax' => '7804363221',
                'email' => 'hvonstackelberg@shaw.ca',
                'category' => 'FAHRENDE',
                'sort_order' => 20,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Lipp\'Quell vom Odin-Aug\'',
                'member_title_details' => '(29.4.143)',
                'real_name' => 'BROECKER, Lothar (Marianne)',
                'profession' => 'Kaufmann',
                'birth_date' => Carbon::create(1948, 11, 17),
                'address' => 'Am Jordanpark 16, D-33175 BAD LIPPSPRINGE, DEUTSCHLAND',
                'phone_home' => '49525253850',
                'phone_fax' => '49525253855',
                'email' => 'ivb.bali01@gmail.com',
                'category' => 'FAHRENDE',
                'sort_order' => 21,
            ],
            
            // EHRENRITTER
            [
                'rank_abbreviation' => null,
                'member_name' => 'Lichterl am Alten Platz',
                'member_title_details' => '(107) Claudium forum, Erküret a.U. 149',
                'real_name' => 'SENEKOWITSCH Gerhard',
                'profession' => 'Unruheständler',
                'birth_date' => Carbon::create(1934, 5, 30),
                'address' => 'Auergasse 2, A-9020 KLAGENFURT, ÖSTERREICH',
                'category' => 'EHRENRITTER',
                'sort_order' => 22,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Brüner der Grafschafter',
                'member_title_details' => '(118) Rocky Mountania, Erküret a.U. 154',
                'real_name' => 'BRUNS Heinz-Jürgen',
                'profession' => null,
                'birth_date' => Carbon::create(1942, 7, 5),
                'address' => '777 East Chestermere Drive, CHESTERMERE LAKE, AB, T1X 1A6',
                'category' => 'EHRENRITTER',
                'sort_order' => 23,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Rohrbruch vom Wörthersee',
                'member_title_details' => '(135) Rocky Mountania, Erküret a.U. 154',
                'real_name' => 'GORITSCHNIG Libert',
                'profession' => 'Installationsmeister',
                'birth_date' => Carbon::create(1944, 12, 6),
                'address' => '79 Applefield Close SE, CALGARY, AB, T2A 7R1',
                'category' => 'EHRENRITTER',
                'sort_order' => 24,
            ],
            
            // BURGFRAUEN IN AHALL WEILENDER SASSEN
            [
                'rank_abbreviation' => null,
                'member_name' => 'Burgfrau Acturus',
                'member_title_details' => 'Frau Elisabeth Swoboda',
                'real_name' => 'SWOBODA Elisabeth',
                'address' => 'Adresse bei Rt. Schöppche zu erfragen',
                'category' => 'BURGFRAUEN IN AHALL WEILENDER SASSEN',
                'sort_order' => 25,
            ],
            [
                'rank_abbreviation' => null,
                'member_name' => 'Burgfrau Künec',
                'member_title_details' => 'Frau Gisela Markwort',
                'real_name' => 'MARKWORT Gisela',
                'address' => 'Adresse bei Rt. Jan Maat zu erfragen',
                'category' => 'BURGFRAUEN IN AHALL WEILENDER SASSEN',
                'sort_order' => 26,
            ],
        ];
        
        foreach ($contacts as $contactData) {
            // Try to find matching member by name
            $member = Member::where('name', 'LIKE', '%' . explode(' ', $contactData['member_name'])[0] . '%')->first();
            
            MemberContact::updateOrCreate(
                [
                    'member_name' => $contactData['member_name'],
                ],
                array_merge($contactData, [
                    'member_id' => $member?->id,
                ])
            );
        }
        
        $this->command->info('Member contacts seeded successfully');
    }
}
